# Detecting human emotion from text they write

## Loading data from files

In [1]:
import numpy as np
import tensorflow
import pandas as pd

In [2]:
with open('train.txt') as file:
    train = file.read()

with open('test.txt') as file:
    test = file.read()

with open('val.txt') as file:
    val = file.read()


In [3]:
train=train.split('\n')
test = test.split('\n')
val = val.split('\n')

In [4]:
train[:5]

['i didnt feel humiliated;sadness',
 'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake;sadness',
 'im grabbing a minute to post i feel greedy wrong;anger',
 'i am ever feeling nostalgic about the fireplace i will know that it is still on the property;love',
 'i am feeling grouchy;anger']

In [5]:
X=[]
y=[]
for sentence in train:
    s = sentence.split(';')
    if(len(s[0])!=0 and len(s[-1])!=0):
        X.append(s[0])
        y.append(s[-1])


In [6]:
X[:10],y[:10]

(['i didnt feel humiliated',
  'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake',
  'im grabbing a minute to post i feel greedy wrong',
  'i am ever feeling nostalgic about the fireplace i will know that it is still on the property',
  'i am feeling grouchy',
  'ive been feeling a little burdened lately wasnt sure why that was',
  'ive been taking or milligrams or times recommended amount and ive fallen asleep a lot faster but i also feel like so funny',
  'i feel as confused about life as a teenager or as jaded as a year old man',
  'i have been with petronas for years i feel that petronas has performed well and made a huge profit',
  'i feel romantic too'],
 ['sadness',
  'sadness',
  'anger',
  'love',
  'anger',
  'sadness',
  'surprise',
  'fear',
  'joy',
  'love'])

In [7]:
len(X),len(y)

(16000, 16000)

In [8]:
for sentence in test:
    s = sentence.split(';')
    if(len(s[0])!=0 and len(s[-1])!=0):
        X.append(s[0])
        y.append(s[-1])

In [9]:
for sentence in val:
    s = sentence.split(';')
    if(len(s[0])!=0 and len(s[-1])!=0):
        X.append(s[0])
        y.append(s[-1])

In [10]:
len(X),len(y)

(20000, 20000)

In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [12]:
tokenizer = Tokenizer()

In [13]:
tokenizer.fit_on_texts(X)

In [14]:
wordcount=len(tokenizer.word_index)
wordcount

17096

In [15]:
tokenized_seq=tokenizer.texts_to_sequences(X)

In [16]:
tokenized_seq[:5]

[[1, 138, 2, 625],
 [1,
  39,
  101,
  59,
  7,
  14,
  522,
  4,
  14,
  3128,
  545,
  31,
  59,
  61,
  128,
  144,
  71,
  1699,
  3,
  21,
  1383],
 [15, 3129, 6, 1228, 4, 290, 1, 2, 495, 420],
 [1, 23, 176, 7, 678, 26, 5, 4770, 1, 57, 46, 8, 12, 21, 69, 29, 5, 3504],
 [1, 23, 7, 1040]]

In [17]:
max_len_seq = 0
for lst in tokenized_seq:
    if len(lst)>max_len_seq:
        max_len_seq = len(lst)

In [18]:
max_len_seq

66

In [19]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [20]:
padded_input_sequences = pad_sequences(tokenized_seq, maxlen = 66, padding='pre')

In [21]:
padded_input_sequences[:2]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    1,  138,    2,  625],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    1,   39,  101,   59,    7,   14,  522,    4,   14, 3128,
         545,   31,   59,   61,  128,  144,   71, 1699,    3,   21, 1383]])

In [22]:
y

['sadness',
 'sadness',
 'anger',
 'love',
 'anger',
 'sadness',
 'surprise',
 'fear',
 'joy',
 'love',
 'sadness',
 'joy',
 'anger',
 'sadness',
 'joy',
 'joy',
 'sadness',
 'sadness',
 'sadness',
 'fear',
 'anger',
 'fear',
 'joy',
 'joy',
 'anger',
 'sadness',
 'sadness',
 'sadness',
 'anger',
 'joy',
 'joy',
 'fear',
 'surprise',
 'anger',
 'joy',
 'joy',
 'joy',
 'joy',
 'anger',
 'joy',
 'joy',
 'joy',
 'joy',
 'joy',
 'sadness',
 'sadness',
 'joy',
 'love',
 'joy',
 'anger',
 'joy',
 'sadness',
 'anger',
 'fear',
 'joy',
 'sadness',
 'sadness',
 'surprise',
 'joy',
 'joy',
 'joy',
 'love',
 'fear',
 'fear',
 'surprise',
 'anger',
 'anger',
 'sadness',
 'love',
 'joy',
 'sadness',
 'sadness',
 'joy',
 'sadness',
 'sadness',
 'sadness',
 'joy',
 'joy',
 'joy',
 'anger',
 'sadness',
 'anger',
 'anger',
 'anger',
 'joy',
 'joy',
 'joy',
 'joy',
 'sadness',
 'fear',
 'love',
 'anger',
 'sadness',
 'anger',
 'love',
 'sadness',
 'joy',
 'joy',
 'sadness',
 'anger',
 'love',
 'joy',
 '

In [23]:
from sklearn.preprocessing import LabelBinarizer

In [24]:
lb = LabelBinarizer()
y_encoded = lb.fit_transform(y)

In [25]:
y_encoded

array([[0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]])

In [26]:
classes = lb.classes_
encoded_values = {}

# Iterate over each class
for i, class_ in enumerate(classes):
    # Create a zero array of length equal to the number of classes
    encoded_value = [0]*len(classes)
    # Set the i-th element to 1
    encoded_value[i] = 1
    # Add the encoded value to the dictionary
    encoded_values[class_] = encoded_value

# Print the classes with their encoded values
for class_, encoded_value in encoded_values.items():
    print(f"{class_}: {encoded_value}")


anger: [1, 0, 0, 0, 0, 0]
fear: [0, 1, 0, 0, 0, 0]
joy: [0, 0, 1, 0, 0, 0]
love: [0, 0, 0, 1, 0, 0]
sadness: [0, 0, 0, 0, 1, 0]
surprise: [0, 0, 0, 0, 0, 1]


In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(padded_input_sequences, y_encoded, test_size=0.2, random_state=0)

In [29]:
X_train

array([[   0,    0,    0, ...,    2,   15, 1076],
       [   0,    0,    0, ...,    9,  136,  199],
       [   0,    0,    0, ...,    3, 6315,  111],
       ...,
       [   0,    0,    0, ...,  321,   24,   74],
       [   0,    0,    0, ...,    2, 5680,  602],
       [   0,    0,    0, ..., 1315,   96, 1210]])

In [31]:
y_test

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       ...,
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0]])

## Model Building

In [32]:
from tensorflow import keras
from tensorflow.keras.layers import *
from keras import Sequential

In [61]:
model2 = Sequential()

In [62]:
model2.add(Embedding(wordcount,100,input_length=max_len_seq))
model2.add(LSTM(256,return_sequences=False))
model2.add(Dense(6,activation ='softmax'))

In [63]:
model2.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [64]:
model2.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 66, 100)           1709600   
                                                                 
 lstm_3 (LSTM)               (None, 256)               365568    
                                                                 
 dense_3 (Dense)             (None, 6)                 1542      
                                                                 
Total params: 2,076,710
Trainable params: 2,076,710
Non-trainable params: 0
_________________________________________________________________


In [65]:
model2.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10)

Epoch 1/10
500/500 [==============================] - 21s 33ms/step - loss: 1.0716 - accuracy: 0.6003 - val_loss: 0.3719 - val_accuracy: 0.8860
Epoch 2/10
500/500 [==============================] - 15s 30ms/step - loss: 0.2062 - accuracy: 0.9278 - val_loss: 0.2422 - val_accuracy: 0.9090
Epoch 3/10
500/500 [==============================] - 15s 31ms/step - loss: 0.0961 - accuracy: 0.9623 - val_loss: 0.1926 - val_accuracy: 0.9300
Epoch 4/10
500/500 [==============================] - 15s 31ms/step - loss: 0.0733 - accuracy: 0.9727 - val_loss: 0.2609 - val_accuracy: 0.9075
Epoch 5/10
500/500 [==============================] - 15s 31ms/step - loss: 0.0495 - accuracy: 0.9805 - val_loss: 0.2079 - val_accuracy: 0.9283
Epoch 6/10
500/500 [==============================] - 15s 31ms/step - loss: 0.0434 - accuracy: 0.9843 - val_loss: 0.3028 - val_accuracy: 0.9115
Epoch 7/10
500/500 [==============================] - 16s 31ms/step - loss: 0.0385 - accuracy: 0.9865 - val_loss: 0.2552 - val_accuracy:

In [66]:
model2.get_weights()

[array([[-0.02241205, -0.10538926, -0.00266965, ..., -0.0072569 ,
         -0.02245034,  0.06024787],
        [-0.01302165, -0.05655713, -0.01811965, ...,  0.00510848,
         -0.02255178,  0.04409413],
        [ 0.03788561,  0.18791129,  0.18736021, ..., -0.23966551,
         -0.07704093,  0.00518413],
        ...,
        [-0.04599478, -0.05542123, -0.04630131, ...,  0.0316685 ,
          0.03048676,  0.00444342],
        [ 0.06188244,  0.04421679, -0.03339681, ..., -0.01806852,
         -0.02237403, -0.04039693],
        [-0.05775288, -0.05470374, -0.09006692, ...,  0.02941612,
          0.04973684,  0.04672414]], dtype=float32),
 array([[ 0.15836257,  0.01868872, -0.13971521, ..., -0.29237318,
         -0.21777058,  0.1529217 ],
        [ 0.24276611, -0.1154795 ,  0.06766376, ..., -0.00191237,
         -0.29320788,  0.19110702],
        [-0.02998305, -0.04773743, -0.09562191, ..., -0.1906846 ,
         -0.03589531, -0.17498167],
        ...,
        [ 0.03242052, -0.00476259,  0.1

In [169]:
text = 'i feel as confused about life as a teenager or as jaded as a year old man'

In [170]:
text=tokenizer.texts_to_sequences([text])

In [171]:
text

[[1, 2, 28, 455, 26, 77, 28, 6, 1951, 34, 28, 814, 28, 6, 193, 274, 367]]

In [172]:
text_padded = pad_sequences(text, maxlen = 66, padding='pre')

In [173]:
text_padded

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    1,    2,   28,  455,   26,   77,
          28,    6, 1951,   34,   28,  814,   28,    6,  193,  274,  367]])

In [174]:
predict =model2.predict(text_padded)

1/1 [==============================] - 0s 58ms/step


In [175]:
predict

array([[1.1363653e-05, 9.9582714e-01, 2.3602861e-06, 6.6662034e-07,
        4.1207997e-03, 3.7688988e-05]], dtype=float32)

In [176]:
arg=np.argmax(predict[0])+1


In [177]:
arg

2

In [178]:
labels = {'anger': 1,
'fear': 2,
'joy': 3,
'love': 4,
'sadness': 5,
'surprise': 6}

In [179]:
for key in labels:
    if labels[key]==arg:
        print (key)

fear


In [119]:
model2.save_weights('emotion.weight.h5')

In [120]:
weight= model2.get_weights()

In [123]:
import pickle

In [180]:
with open('weights_emotion.pkl','wb') as f:
    pickle.dump(weight,f)